name: test pr

on:
  pull_request:

jobs:
  publish:
    runs-on: [global-general]
    steps:
      - uses: actions/checkout@v1
      - name: unit-tests
        continue-on-error: true
        run: |
          whoami
          pwd
          ls  
